<a href="https://colab.research.google.com/github/VitorGomesder4/numphy-studies/blob/main/som_mul_de_matrizes_EDNARDO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Faça um programa que some e multiplique Matrizes:
***

**Professor se quiser saber como o codigo funciona em cada linha deixei um comentario explicando**
***

In [ ]:
import numpy as np #importa a biblioteca numpy que é usada para manipulação, criação, operação de arrays/matrizes

matriz_A = np.array([
    [1, 3, -2, 4, 7, 2],
    [5, 5, 1, -1, 1, -1],
    [9, 15, 11, 12, 7, 2],
    [3, -3, -2, -8, 7, 4],
    [5, -2, 7, 8, -3, -2],
    [22, 53, -10, 4, -1, -3]]) #Separo uma variavel matriz_A usando a função np.array para criar uma matriz de 6 linhas/index

print("A = \n{}\n".format(matriz_A)) #Print da matriz A

matriz_B = np.array([
    [1, 5, 3, 2, 1, 9],
    [5, 6, -7, 5, 0, 0],
    [1, -1, 1, 1, 2, 4],
    [5, 10, -15, 25, 21, 23],
    [17, 0, -27, -3, 74, 9],
    [2, 21, -20, 42, 0, 0]]) #Separo uma variavel matriz_B usando a função np.array para criar uma matriz de 6 linhas/index

print("B = \n{}\n".format(matriz_B)) #Print da matriz A

soma_de_AB = matriz_A + matriz_B #Variavel que guarda a soma das duas matrizes

print("A + B = \n{}\n".format(soma_de_AB)) #Print do resultado da soma

multi_de_AB = np.matmul(matriz_A, matriz_B) #Variavel que guarda a multiplicação das duas matrizes

print("A * B = \n{}".format(multi_de_AB)) #Print do resultado da multiplicação

A = 
[[  1   3  -2   4   7   2]
 [  5   5   1  -1   1  -1]
 [  9  15  11  12   7   2]
 [  3  -3  -2  -8   7   4]
 [  5  -2   7   8  -3  -2]
 [ 22  53 -10   4  -1  -3]]

B = 
[[  1   5   3   2   1   9]
 [  5   6  -7   5   0   0]
 [  1  -1   1   1   2   4]
 [  5  10 -15  25  21  23]
 [ 17   0 -27  -3  74   9]
 [  2  21 -20  42   0   0]]

A + B = 
[[  2   8   1   6   8  11]
 [ 10  11  -6   4   1  -1]
 [ 10  14  12  13   9   6]
 [  8   7 -17  17  28  27]
 [ 22  -2 -20   5  71   7]
 [ 24  74 -30  46  -1  -3]]

A * B = 
[[ 157  107 -309  178  599  156]
 [  41   23  -11  -34   60   35]
 [ 278  286 -476  467  801  464]
 [  73    3 -121  -64  349 -102]
 [ -13   44   37  132  -35  230]
 [ 274  415 -288  276   12  241]]
